import 'package:flutter/material.dart';

class TransactionPageViewModel extends ChangeNotifier {
  TextEditingController frameBrand = TextEditingController(),
      frameBarcode = TextEditingController(),
      lensType = TextEditingController(),
      lensTint = TextEditingController(),
      contactController = TextEditingController(),
      specr1 = TextEditingController(),
      specr2 = TextEditingController(),
      specr3 = TextEditingController(),
      specr4 = TextEditingController(),
      specr5 = TextEditingController(),
      specl1 = TextEditingController(),
      specl2 = TextEditingController(),
      specl3 = TextEditingController(),
      specl4 = TextEditingController(),
      specl5 = TextEditingController(),
      lensr1 = TextEditingController(),
      lensr2 = TextEditingController(),
      lensr3 = TextEditingController(),
      lensr4 = TextEditingController(),
      lensr5 = TextEditingController(),
      lensl1 = TextEditingController(),
      lensl2 = TextEditingController(),
      lensl3 = TextEditingController(),
      lensl4 = TextEditingController(),
      lensl5 = TextEditingController(),
      frameAmount = TextEditingController(),
      lensAmount = TextEditingController(),
      clAmount = TextEditingController(),
      total = TextEditingController(),
      deposit = TextEditingController(),
      balance = TextEditingController();
}
